### ISSUE TITLE
Illegal Moves

### ISSUE THREAD

**Issue by Notproffesionalcoder** [DanielSharkov/svelte-chess#1]
Illegal moves allowed such as king can go to king and other

**Comment by DanielSharkov** [comment]
Hi @Notproffesionalcoder !
As I mentioned in the readme, it still isn't fully playable. Maybe "still" isn't the proper term for that anymore, as of now I guess "forever" makes more sense.
It was just a sideproject. It never wasn't a big thing - but a cool thing! Of course I was planing to make it playable, but as life is changing, so the priorities do too. So far I wasn't able to spare the time for this project. I guess that's how this story ends. 😄

Feel free to craft your own chess game, with the help of this code - as it's now under the MIT license! :)
